# input
batch: 100
input_length: 0.32
input_gap_mean: 0.6
input_gap_std: 0.05
arrival_rate_ppm: 180

# upstream
L_upstream: 2.0
j_u_max: 100.0
v_u_max: 2.0
a_u_max: 3.5

# buffer
jmax: 100.0
Vmax: 3.0
Amax: 8.5

# solver: quintic
solver: scurve
L_buffer: 3
n_buffer_seg: 6
v_buff_out: 2.5 # v^{BR}

start_margin: 1 # the fraction of the input length, that must be on the buffer, before buffer control may commence.
end_margin: 0.0

# registrar
L_registrar: 1.0
n_reg_seg: 1

# downstream
L_downstream: 2.0
eta_s: 1.875   # slot_length = eta_s * input_length
eta_r: 1.2     # slot_rate   = eta_r * arrival_rate_ppm
